### ISSUE TITLE
Wiki2018 and DPR_nqsingle_official index length is different?

### ISSUE THREAD

**Issue by Ankur3107** [KNOT-FIT-BUT/scalingQA#1]
Hi Team,

I have tried to use DPR_nqsingle_official.h5 and wiki2018_dpr_blocks.db for my project but their length seems different, am I doing wrong somewhere or is it like that only?

- DPR_nqsingle_official.h5 : **21015320*768**
- wiki2018_dpr_blocks.db ids length: **21015324**

Please Help  me!

**Comment by MFajcik** [comment]
Hi @Ankur3107, thanks for reaching out.  You are doing alright. The lengths are **indeed different**.  In particular, representations for the last 4 passages are missing. This applies for both, `DPR_nqsingle_official.h5` and `DPR_multiset_official.h5` (I have checked this manually). 

However, it is unlikely this would have any significant impact in practice. To avoid confusion, **we will update the downloadable indices soon**, so they would correspond to the released database. I will close this issue after their update.

The reason why were they missing is probably linked to DPR's released files (our index matrix is just a concatenation of their index files), as they likely also didn't contain these. The DPR repo recently went through some updates, however even now if you download their index files ([for example here](https://github.com/facebookresearch/DPR/blob/142d448f528031efc711b70fe2d5d8a6b671fea8/dpr/data/download_data.py#L204)), there is not exactly 21,015,324 embeddings but just 21,015,300.

**Comment by Ankur3107** [comment]
@MFajcik Thanks for the clarification!

**Comment by MFajcik** [comment]
I have tried adding those 4 missing embeddings, but interestingly this changed results slightly (insignificantly, e.g. -0.2EM on NQ). To keep the numbers exactly the same as we reported, we decided to keep the indices as they are.
